#!/usr/bin/env ruby
require 'listpager/client_terminal'

[$stdin, $stdout].each do |io|
  io.sync = true
  io.reopen('/dev/null') if io.tty?
end

begin
  Listpager::ClientTerminal.new.run
rescue Interrupt
  $stdout.puts "interrupt"
  $stdout.flush
rescue SystemCallError => e
  $stderr.puts "#{$0}: #{e.message}"
  exit 1
end
